FLAGS=-Wall -O0 -g
COMP=g++

c_sr_15: cycl_sr_15.cpp
	$(COMP) $(FLAGS) $< -o $@

c_sl_3: cycl_sl_3.cpp
	$(COMP) $(FLAGS) $< -o $@

c_l_1: cycl_l_1.cpp
	$(COMP) $(FLAGS) $< -o $@

cond_sl_1: cond_sl_1.cpp
	$(COMP) $(FLAGS) $< -o $@

cond_sl_3: cond_sl_3.cpp
	$(COMP) $(FLAGS) $< -o $@

cond_sl_4: cond_sl_4.cpp
	$(COMP) $(FLAGS) $< -o $@


